name: Update Amazon Proxies

on:
  schedule:
    - cron: '0 */3 * * *'  # Run every 3 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
    
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pysocks
          
      - name: Pull latest changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
      
      - name: Run Amazon proxy test
        run: |
          python amazon_proxy_test.py 32 http,socks4,socks5 1

      - name: Commit updated proxy files
        run: |
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Proxies ($(date '+%F %H:%M %Z'))"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 